login/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views # Importa las vistas de autenticación de Django

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
    # URLs para el restablecimiento de contraseña
    # Vista para solicitar el correo de restablecimiento
    path('password_reset/', 
        auth_views.PasswordResetView.as_view(template_name='paginas/restablecimiento_contrasena.html'), 
        name='password_reset'),
    # Vista de confirmación de que el correo fue enviado
    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='paginas/restablecimiento_done.html'), 
        name='password_reset_done'),

    # Vista del enlace que llega en el correo, para cambiar la contraseña
    #reset: ayuda a identificar que esta dirección es para confirmar un restablecimiento de contraseña.
    #<uidb64>: 
    # uid:  Es el número de ID único que tiene el usuario en tu base de datos.
    # b64: Significa "Base64". El ID del usuario se codifica en formato Base64. Esto no es por seguridad, sino para asegurar que el ID se pueda transmitir de forma segura en una URL sin caracteres extraños.
    #<token>: es un token único generado para la solicitud de restablecimiento de contraseña. Este token asegura que la solicitud es válida y no ha sido manipulada.
    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='paginas/restablecimiento_confirm.html'), 
        name='password_reset_confirm'),

    # Vista de confirmación de que la contraseña se cambió con éxito
    path('reset/done/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='paginas/restablecimiento_complete.html'), 
        name='password_reset_complete'),
]

unisalud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
#from django.contrib.auth import views as auth_views
from prof_salud import views

urlpatterns = [
    # raíz redirige a la app de paciente (evita url='' que genera bucle/410)
    #path('', RedirectView.as_view(url='/paciente/', permanent=False)),
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('a/', views.login_prof_salud, name='login_prof_salud'),
    path('usuario/', include('usuario.urls')),
    path('profesionalS/', include('prof_salud.urls')),
    path('administrativo/', include('administrativo.urls')),
    # usar LoginView directo o descomentar la línea con include si prefieres todas las rutas de auth
    #path('login/', auth_views.LoginView.as_view(), name='login'),  # alternativa: path('accounts/', include('django.contrib.auth.urls')),
]

login/models.py
from django.db import models

usuario/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password #para codificar y verificar las contraseñas de forma segura

class Roles(models.Model): 
    id_rol = models.AutoField(primary_key=True, db_comment='ID autoincremental del roles')
    nombre_rol = models.CharField(unique=True, max_length=50, db_comment='Nombre de los roles: paciente, profesional_salud, laboratorista, recepcionista, admin_centro_medico')
    descripcion = models.TextField(blank=True, null=True, db_comment='Descripcion de los roles para mayor claridad, opcional')

    class Meta:
        managed = True
        db_table = 'roles'
        verbose_name = 'Rol'
        verbose_name_plural = 'Roles'

    def __str__(self):
        return self.nombre_rol

class Usuarios(models.Model):
    id_usuario = models.AutoField(primary_key=True, db_comment='ID autoincremental del usuario')
    id_rol = models.ForeignKey('Roles', models.DO_NOTHING, db_column='id_rol', db_comment='Rol asignado para pacientes, profesional salud, recepcionista, laboratorista, adm centro')
    nombre_usuario = models.CharField(unique=True, max_length=50, db_comment='Login unico para el usuario')
    contrasena = models.CharField(max_length=255, db_comment='Contrasena que crea el usuario')
    email = models.CharField(unique=True, max_length=100, blank=True, null=True, db_comment='Correo principal-login del usuario')
    
    class Meta:
        managed = True
        db_table = 'usuarios'

    def __str__(self):
        return self.nombre_usuario

#manejar contraseñas de forma segura
#set_password: toma la contraseña en texto plano y la codifica antes de almacenarla en la base de datos.
    def set_password(self, raw_password):
        self.contrasena = make_password(raw_password)

#check_password: verifica si la contraseña en texto plano coincide con la contraseña codificada almacenada.
    def check_password(self, raw_password):
        return check_password(raw_password, self.contrasena)

class tipoidentificacion(models.Model):
    id_tipo_identificacion = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    identificacion = models.CharField(unique=True, max_length=50, db_comment='Abreviatura del tipo de identificacion: CC, TI, etc')
    nombre_identificacion = models.CharField(max_length=50, db_comment='Nombre completo del tipo de identificacion: Cédula de Ciudadanía, Tarjeta de Identidad, etc')
    descripcion = models.TextField(blank=True, null=True, db_comment='Descripcion opcional')

    class Meta:
        managed = True
        db_table = 'tipo_identificacion'
        verbose_name = 'Tipo de Identificacion'
        verbose_name_plural = 'Tipos de Identificacion'

    def __str__(self):
        return self.nombre_identificacion


class genero(models.Model):
    id_genero = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    nombre_genero = models.CharField(unique=True, max_length=20, db_comment='Ej: Masculino, Femenino, No Binario, etc')

    
    def __str__(self):
        return self.nombre_genero
    
    class Meta:
        managed = True
        db_table = 'genero'


class gruporh(models.Model):
    id_rh = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    tipo_rh = models.CharField(unique=True, max_length=3, db_comment='Ej: A+, B-, etc')

    
    def __str__(self):
        return self.tipo_rh
    
    class Meta:
        managed = True
        db_table = 'grupo_rh'


class estadocivil(models.Model):
    id_estado_civil = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    nombre_estado = models.CharField(unique=True, max_length=20, db_comment='Ej: soltero, casado, etc')

    class Meta:
        managed = True
        db_table = 'estado_civil'

    def __str__(self):
        return self.nombre_estado


class estratosocioeconomico(models.Model):
    id_estrato = models.IntegerField(primary_key=True, db_comment='ID del 1 al 6')
    descripcion = models.CharField(max_length=100, db_comment='Ej: Bajo, Medio, alto')

    class Meta:
        managed = True
        db_table = 'estrato_socioeconomico'

    def __str__(self):
        return f'Estrato {self.id_estrato}'


class regionsalud(models.Model):
    id_region = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    nombre_region = models.CharField(unique=True, max_length=100, db_comment='Nombre de la region Ej: caribe, eje cafetero, sur occidente, etc')
    descripcion = models.TextField(blank=True, null=True, db_comment='Descripcion')

    class Meta:
        managed = True
        db_table = 'regionsalud'

    def __str__(self):
        return self.nombre_region


class departamento(models.Model):
    id_departamento = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    nombre_departamento = models.CharField(max_length=100, db_comment='Nombre del departamento')
    id_region = models.ForeignKey('regionsalud', models.DO_NOTHING, db_column='id_region', blank=True, null=True, db_comment='Referencia a REGION_SALUD')
    codigo_dane = models.CharField(max_length=10, blank=True, null=True, db_comment='Codigo DANE para identificar oficialmente c-depto.')

    class Meta:
        managed = True
        db_table = 'departamento'

    def __str__(self):
        return self.nombre_departamento


class ciudad(models.Model):
    id_ciudad = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    nombre_ciudad = models.CharField(max_length=100, db_comment='Nombre de la ciudad')
    id_departamento = models.ForeignKey('departamento', models.DO_NOTHING, db_column='id_departamento', db_comment='Referencia a DEPARTAMENTO')
    codigo_dane = models.CharField(max_length=10, blank=True, null=True, db_comment='Codigo DANE para identificar oficialmente c-ciudad')

    class Meta:
        managed = True
        db_table = 'ciudad'

    def __str__(self):
        return self.nombre_ciudad


class redessalud(models.Model):
    id_red = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    nombre_red = models.CharField(unique=True, max_length=150, db_comment='Nombre de la red: RIPSS (Redes integrales de prestadores de servicios de salud)')
    descripcion = models.TextField(blank=True, null=True, db_comment='Descripcion')
    id_region = models.ForeignKey('regionsalud', models.DO_NOTHING, db_column='id_region', blank=True, null=True, db_comment='Referencia a REGION_SALUD')
    estado_red = models.CharField(max_length=8, blank=True, null=True, db_comment='Esta activa, inactiva')

    class Meta:
        managed = True
        db_table = 'redessalud'

    def __str__(self):
        return self.nombre_red


class nivelesatencion(models.Model):
    id_nivel = models.IntegerField(primary_key=True, db_comment='ID del nivel (1 a 3)')
    nombre_nivel = models.CharField(max_length=50, db_comment='de acuerdo al grado de complejidad en salud: primer nivel-atencion basica')
    descripcion = models.TextField(blank=True, null=True, db_comment='Descripcion')

    class Meta:
        managed = True
        db_table = 'nivelesatencion'

    def __str__(self):
        return self.nombre_nivel


class centrosmedicos(models.Model):
    id_centro_medico = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    nombre_centro = models.CharField(max_length=150, db_comment='Nombre del centro medico')
    id_red_salud = models.ForeignKey('redessalud', models.DO_NOTHING, db_column='id_red_salud', blank=True, null=True, db_comment='Referencia a redessalud')
    id_nivel_atencion = models.ForeignKey('nivelesatencion', models.DO_NOTHING, db_column='id_nivel_atencion', db_comment='Referencia a NIVELES_ATENCION')
    id_ciudad = models.ForeignKey('ciudad', models.DO_NOTHING, db_column='id_ciudad', db_comment='Referencia a CIUDAD')
    direccion = models.CharField(max_length=255, db_comment='Direccion centro medico')
    latitud = models.DecimalField(max_digits=10, decimal_places=8, blank=True, null=True, db_comment='Latitud, localizacion geografica')
    longitud = models.DecimalField(max_digits=10, decimal_places=8, blank=True, null=True, db_comment='Longitud, localizacion geografica')
    telefono = models.CharField(max_length=15, blank=True, null=True, db_comment='Telefono centro medico')
    celular = models.CharField(max_length=15, blank=True, null=True, db_comment='Celular centro medico')
    correo = models.CharField(max_length=100, blank=True, null=True, db_comment='Correo entro medico')
    sitio_web = models.CharField(max_length=150, blank=True, null=True, db_comment='Sitio web centro medico')
    codigo_habilitacion = models.CharField(unique=True, max_length=50, blank=True, null=True, db_comment='Codigo de habilitacion REPS')
    fecha_habilitacion = models.DateField(blank=True, null=True, db_comment='Fecha de habilitacion REPS')
    estado_centro = models.CharField(max_length=10, blank=True, null=True, db_comment='Esta activa, inactiva')

    class Meta:
        managed = True
        db_table = 'centrosmedicos'

    def __str__(self):
        return self.nombre_centro


class eps(models.Model):
    id_eps = models.AutoField(primary_key=True, db_comment='ID autoincremental')
    nombre_eps = models.CharField(unique=True, max_length=100, db_comment='Nombre de la EPS')
    nit = models.CharField(max_length=20, blank=True, null=True, db_comment='NIT de la EPS')
    direccion = models.CharField(max_length=255, blank=True, null=True, db_comment='Direccion de la EPS')
    telefono = models.CharField(max_length=15, blank=True, null=True, db_comment='Telefono de la EPS')
    correo = models.CharField(max_length=100, blank=True, null=True, db_comment='Correo de la EPS')
    estado_eps = models.CharField(max_length=8, blank=True, null=True, db_comment='Esta activa, inactiva')

    class Meta:
        managed = True
        db_table = 'eps'

    def __str__(self):
        return self.nombre_eps


class tiposafiliacion(models.Model):

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout # para manejar la sesión del usuario
from django.contrib import messages
from usuario.models import Usuarios, pacientes, profesionalsalud

def login_view(request):
    if request.method == 'POST':
        nombre_usuario = request.POST.get('nombre_usuario')
        contrasena = request.POST.get('contrasena')
        try:
            usuario = Usuarios.objects.get(nombre_usuario=nombre_usuario)
            if usuario.check_password(contrasena):
                request.session['id_usuario'] = usuario.id_usuario
                request.session['nombre_rol'] = usuario.id_rol.nombre_rol # Corregido: La relación es a través de id_rol

                if usuario.id_rol.nombre_rol == 'paciente': # Corregido: La relación es a través de id_rol
                    try:
                        paciente = pacientes.objects.get(usuario=usuario)
                        request.session['id_paciente'] = paciente.id_paciente
                        return redirect('inicio-usuario')
                    except pacientes.DoesNotExist:
                        messages.error(request, 'Este usuario no tiene un perfil de paciente asociado.')
                        return render(request, 'paginas/login.html')
                
                elif usuario.id_rol.nombre_rol in ['profesional_salud', 'laboratorista', 'recepcionista', 'admin_centro_medico']: # Corregido: La relación es a través de id_rol
                    try:
                        prof_salud = profesionalsalud.objects.get(usuario=usuario)
                        request.session['id_profesional'] = prof_salud.id_profesional
                        return redirect('inicio_prof_salud')
                    except profesionalsalud.DoesNotExist:
                        messages.error(request, 'Este usuario no tiene un perfil de profesional de salud asociado.')
                        return render(request, 'paginas/login.html')
                else:
                    messages.error(request, 'Rol no reconocido o sin página de inicio definida.')
            else:
                messages.error(request, 'Nombre de usuario o contraseña incorrectos.')
        except Usuarios.DoesNotExist:
            messages.error(request, 'Nombre de usuario o contraseña incorrectos.')
    return render(request, 'paginas/login.html')

# para cerrar sesion y redirige al login
def logout_view(request):
    logout(request)
    return redirect('login')

login/templates/paginas/login.html
{% extends "plantilla.html" %}
{% load static %}
{% block title %}Iniciar Sesión{% endblock title %}

{% block content %}

<section class="main" style="padding-top:30px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="pt-3 text-center">
                    <h1>Bienvenido a Unisalud!</h1>
                    <p>Para ingresar al sistema por favor inicie sesión aquí</p>
                </div>
                <div class="border border-dark rounded p-4 my-5 div-main">
                    <!-- Contenedor del formulario de login -->
                    <div id="loginFormContainer">
                        <h1 class="text-center">Inicio de sesión</h1>
                        <form method="post" action="{% url 'login' %}">
                            {% csrf_token %}
                            <section class="mt-3">
                                <!-- Mostrar mensajes de error -->
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert alert-danger text-center" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}

                                <!-- Fila para el nombre de usuario -->
                                <div class="row mb-3">
                                    <label for="inputUsername" class="col-md-4 col-form-label text-md-end">Nombre de usuario</label>
                                    <div class="col-md-8">
                                        <input type="text" name="nombre_usuario" id="inputUsername" class="form-control" placeholder="Ingresa aquí tu nombre de usuario" required>
                                    </div>
                                </div>
                                <!-- Fila para la contraseña -->
                                <div class="row mb-3">
                                    <label for="password" class="col-md-4 col-form-label text-md-end">Contraseña</label>
                                    <div class="col-md-8">
                                        <div class="input-group">
                                            <input type="password" name="contrasena" class="form-control" id="password" placeholder="Ingrese aquí su contraseña" required>
                                            <button class="btn btn-primary" type="button" id="togglePasswordBtn">Ver</button>
                                        </div>
                                    </div>
                                    <div class="text-center mt-3">
                                        <a href="{% url 'password_reset' %}" class="btn btn-sm btn-primary me-2" role="button">Olvidé mi contraseña</a>
                                    </div>
                                </div>
                            </section>
                            <div class="text-center mt-4">
                                <button type="submit" class="btn btn-lg btn-success custom-highlight-btn">Iniciar Sesión</button>
                            </div>
                        </form>
                        <div class="opciones-secundarias text-center mt-3">
                            <hr>
                            <p>¿No tiene una cuenta?
                                <a href="{% url 'registrarse' %}" class="btn btn-sm btn-primary" role="button">Registrese aquí</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

{% block script %}
<script>
// Espera a que el documento esté completamente cargado
    document.addEventListener('DOMContentLoaded', function() {
        const passwordInput = document.getElementById('password');
        const togglePasswordBtn = document.getElementById('togglePasswordBtn');

        togglePasswordBtn.addEventListener('click', function() {
            // Cambia el tipo del input de password a text y viceversa
            const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordInput.setAttribute('type', type);
            // Cambia el texto del botón
            this.textContent = type === 'password' ? 'Ver' : 'Ocultar';
        });
    });
</script>
{% endblock script %}

login/templates/paginas/restablecimiento_complete.html
{% extends "plantilla.html" %}
{% load static %}
{% block title %}Contraseña Restablecida{% endblock title %}

{% block content %}
<section class="main" style="padding-top:30px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="border border-dark rounded p-4 my-5 div-main text-center">
                    <h1>¡Contraseña Restablecida!</h1>
                    <p class="mt-3">
                        Tu contraseña ha sido cambiada exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.
                    </p>
                    <a href="{% url 'login' %}" class="btn btn-lg btn-success custom-highlight-btn mt-3">Iniciar Sesión</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

login/templates/paginas/restablecimiento_confirm.html
{% extends "plantilla.html" %}
{% load static %}
{% block title %}Ingresar Nueva Contraseña{% endblock title %}

{% block content %}
<section class="main" style="padding-top:30px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="border border-dark rounded p-4 my-5 div-main">
                    <h1 class="text-center">Establecer Nueva Contraseña</h1>
                    {% if validlink %}
                        <p class="text-center mt-3">Por favor, ingresa tu nueva contraseña dos veces para verificar que la has escrito correctamente.</p>
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="text-center mt-4">
                                <button type="submit" class="btn btn-lg btn-success custom-highlight-btn">Cambiar mi contraseña</button>
                            </div>
                        </form>
                    {% else %}
                        <p class="alert alert-danger text-center mt-3">
                            El enlace para restablecer la contraseña no es válido, posiblemente porque ya ha sido utilizado. 
                            Por favor, solicita un nuevo restablecimiento de contraseña.
                        </p>
                        <div class="text-center">
                            <a href="{% url 'password_reset' %}" class="btn btn-main">Solicitar nuevo enlace</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

login/templates/paginas/restablecimiento_contrasena.html
{% extends "plantilla.html" %}
{% load static %}
{% block title %}Restablecer Contraseña{% endblock title %}

{% block content %}
<section class="main" style="padding-top:30px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="border border-dark rounded p-4 my-5 div-main">
                    <h1 class="text-center">Restablecer Contraseña</h1>
                    <p class="text-center mt-3">
                        ¿Olvidaste tu contraseña? Ingresa tu dirección de correo electrónico a continuación y te enviaremos las instrucciones para establecer una nueva.
                    </p>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_email" class="form-label">Correo Electrónico:</label>
                            {{ form.email }}
                        </div>
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-lg btn-success custom-highlight-btn">Enviar Correo</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

login/templates/paginas/restablecimiento_done.html
{% extends "plantilla.html" %}
{% load static %}
{% block title %}Correo Enviado{% endblock title %}

{% block content %}
<section class="main" style="padding-top:30px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="border border-dark rounded p-4 my-5 div-main text-center">
                    <h1>Revisa tu correo</h1>
                    <p class="mt-3">
                        Te hemos enviado un correo electrónico con las instrucciones para restablecer tu contraseña. Si no lo encuentras, revisa tu carpeta de spam.
                    </p>
                    <a href="{% url 'login' %}" class="btn btn-main mt-3">Volver al inicio de sesión</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}